Repository msingr/csvGeom, pull requests merged in 2023-06, with the labels that each got.

#13 remove excess brackets in single point creation (output formatter)
  enums/outputType.py
  examples/testpolygon_für_geojson_2.csv
  geojson/multiPoint.py
  gui.py
  modeller.py
  outputFormatter.py
Labels: bug

#25 Remove exe
  csvGeom.py
  enums/outputType.py
  examples/csvGeom_testdata.csv
  geojson/coordinate.py
  geojson/feature.py
  geojson/featureCollection.py
  geojson/line.py
  geojson/lineString.py
  geojson/multiLineString.py
  geojson/multiPoint.py
  geojson/multiPolygon.py
  geojson/point.py
  geojson/polygon.py
  gui.py
  inputReader.py
  modeller.py
  outputFormatter.py
Labels: quality

#26 Feature multi geometries
  csvGeom.py
  geojson/feature.py
  geojson/featureCollection.py
  geojson/multiLineString.py
  geojson/multiPoint.py
  geojson/multiPolygon.py
  geojson/point.py
  geojson/polygon.py
  inputReader.py
  modeller.py
  utils/logger.py
Labels: enhancement

#39 Added localization for gui
  csvGeom.py
  gui.py
  inputReader.py
  localization/de.json
  localization/en.json
  modeller.py
  utils/util.py
Labels: enhancement
